type Status='NORMAL'|'DETECTED'|'ISOLATED'|'DIAGNOSING'|'RECOVERING'|'VERIFYING'|'CANARY'|'RESTORING_ADMISSION';
interface Env { CONTROL_VERSION?: string; }
const json=(b:unknown,s=200,r=crypto.randomUUID())=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json','x-request-id':r}});
const ALLOWED:Record<Status,Status[]>={NORMAL:['DETECTED'],DETECTED:['ISOLATED'],ISOLATED:['DIAGNOSING'],DIAGNOSING:['RECOVERING','NORMAL'],RECOVERING:['VERIFYING'],VERIFYING:['CANARY','RECOVERING'],CANARY:['RESTORING_ADMISSION','RECOVERING'],RESTORING_ADMISSION:['NORMAL','RECOVERING']};
export default {async fetch(request:Request,env:Env){const rid=request.headers.get('x-request-id')?.slice(0,128)||crypto.randomUUID();try{const u=new URL(request.url);
if(request.method==='GET'&&u.pathname==='/health')return json({status:'READY',service:'d1-fabric-w06-control-recovery',version:'0.1.0',control_version:env.CONTROL_VERSION??'1'},200,rid);
if(request.method==='POST'&&u.pathname==='/v1/recovery/transition'){const b=await request.json() as {from?:Status;to?:Status;reason?:string};if(!b.from||!b.to||!ALLOWED[b.from]?.includes(b.to))return json({code:'INVALID_RECOVERY_TRANSITION'},409,rid);return json({accepted:true,from:b.from,to:b.to,reason:b.reason??null,bounded:true,idempotent_transition_key:`${b.from}->${b.to}`},200,rid);}
if(request.method==='POST'&&u.pathname==='/v1/migration/plan'){const b=await request.json() as {shard_id?:number;source?:string;target?:string;current_epoch?:number;target_epoch?:number};if(!Number.isInteger(b.shard_id)||!b.source||!b.target||!Number.isInteger(b.current_epoch)||b.target_epoch!==b.current_epoch+1)return json({code:'INVALID_EPOCH_TRANSITION'},400,rid);return json({migration_id:crypto.randomUUID(),phase:'PLAN',shard_id:b.shard_id,source:b.source,target:b.target,steps:['PLAN','PREPARE','COPY','VERIFY','FENCE','COMMIT_OWNERSHIP','ADVANCE_EPOCH','SERVE','RETIRE_SOURCE'],from_epoch:b.current_epoch,to_epoch:b.target_epoch},200,rid);}
return json({code:'NOT_FOUND'},404,rid);}catch(e){return json({code:e instanceof Error?e.message:'INTERNAL_ERROR'},500,rid)}}};
