import assert from "node:assert/strict";
import { test } from "node:test";
import { executeWrite, type D1DatabaseLike, type D1PreparedStatementLike, type D1ResultLike, type WriteRequest } from "../src/write.ts";
interface Row { tenant_id: string; principal_scope: string; operation: string; operation_version: string; contract_version: string; idempotency_key: string; state: string; result_json: string | null; }
class FakeStatement implements D1PreparedStatementLike {
  private readonly db: FakeD1; readonly sql: string; readonly values: unknown[];
  constructor(db: FakeD1, sql: string, values: unknown[] = []) { this.db = db; this.sql = sql; this.values = values; }
  bind(...values: unknown[]): D1PreparedStatementLike { return new FakeStatement(this.db, this.sql, values); }
  async first<T>(): Promise<T | null> { const [tenant, principal, operation, operationVersion, contractVersion, key] = this.values as string[]; const row = this.db.idempotency.find((r) => r.tenant_id === tenant && r.principal_scope === principal && r.operation === operation && r.operation_version === operationVersion && r.contract_version === contractVersion && r.idempotency_key === key); return row ? ({ state: row.state, tenantId: row.tenant_id, principalScope: row.principal_scope, operation: row.operation, operationVersion: row.operation_version, contractVersion: row.contract_version, resultJson: row.result_json } as T) : null; }
}
class FakeD1 implements D1DatabaseLike {
  idempotency: Row[] = []; mutationCount = 0; failMutation = false; commitThenThrow = false;
  prepare(sql: string): D1PreparedStatementLike { return new FakeStatement(this, sql); }
  async batch(statements: readonly D1PreparedStatementLike[]): Promise<D1ResultLike[]> { assert.equal(statements.length, 3); const cloned = this.idempotency.map((r) => ({ ...r })); const originalCount = this.mutationCount; const [claim, , commit] = statements as FakeStatement[]; const identity = claim.values as string[]; if (this.idempotency.some((r) => r.tenant_id === identity[0] && r.principal_scope === identity[1] && r.operation === identity[2] && r.operation_version === identity[3] && r.contract_version === identity[4] && r.idempotency_key === identity[5])) throw new Error("UNIQUE_IDEMPOTENCY_CONFLICT"); this.idempotency.push({ tenant_id: identity[0], principal_scope: identity[1], operation: identity[2], operation_version: identity[3], contract_version: identity[4], idempotency_key: identity[5], state: "IN_FLIGHT", result_json: null }); if (this.failMutation) { this.idempotency = cloned; this.mutationCount = originalCount; throw new Error("MUTATION_FAILED"); } this.mutationCount += 1; const row = this.idempotency[this.idempotency.length - 1]; row.state = "COMMITTED"; row.result_json = (commit.values as unknown[])[0] as string; if (this.commitThenThrow) throw new Error("RESPONSE_LOST_AFTER_COMMIT"); return [{ meta: { rows_written: 1 } }, { meta: { rows_written: 1 } }, { meta: { rows_written: 1 } }]; }
}
function request(overrides: Partial<WriteRequest> = {}): WriteRequest { return { requestId: "req-1", tenantId: "tenant-1", principalScope: "content:write", operation: "content.publish", operationVersion: "1", contractVersion: "D1F-3.0-MASTER-v1.0", idempotencyKey: "idem-1", logicalTargetId: "logical-1", executionEpoch: "epoch-1", mutationSql: "INSERT INTO content VALUES (?)", mutationBindings: ["x"], replayResult: { accepted: true }, expectedRowsWritten: 1, budget: { d1Statements: 5, rowsWritten: 3, payloadBytes: 1024 }, deadlineAt: Date.now() + 10_000, actualFanout: 1, ...overrides }; }
test("first mutation commits atomically and consumes four statements", async () => { const db = new FakeD1(); const result = await executeWrite(db, request()); assert.equal(result.status, "COMMITTED"); assert.equal(result.ledger.reserved.d1Statements, 0); assert.equal(result.ledger.consumed.d1Statements, 4); assert.equal(result.ledger.released.d1Statements, 1); assert.equal(result.ledger.consumed.rowsWritten, 3); assert.equal(db.mutationCount, 1); });
test("committed duplicate replays with one lookup and no mutation", async () => { const db = new FakeD1(); await executeWrite(db, request()); const result = await executeWrite(db, request({ requestId: "req-2" })); assert.equal(result.status, "REPLAYED"); assert.deepEqual(result.result, { accepted: true }); assert.equal(result.ledger.consumed.d1Statements, 1); assert.equal(db.mutationCount, 1); });
test("mutation failure rolls back idempotency claim atomically", async () => { const db = new FakeD1(); db.failMutation = true; const result = await executeWrite(db, request()); assert.equal(result.status, "FAILED"); assert.equal(result.error, "WRITE_FAILED"); assert.equal(db.mutationCount, 0); assert.equal(db.idempotency.length, 0); });
test("response loss after commit resolves authoritative state without retry", async () => { const db = new FakeD1(); db.commitThenThrow = true; const result = await executeWrite(db, request()); assert.equal(result.status, "REPLAYED"); assert.equal(result.ledger.consumed.d1Statements, 5); assert.equal(db.mutationCount, 1); });
test("budget hard-stop rejects before D1 dispatch", async () => { const db = new FakeD1(); const result = await executeWrite(db, request({ budget: { d1Statements: 4, rowsWritten: 3, payloadBytes: 1024 } })); assert.equal(result.error, "BUDGET_EXCEEDED"); assert.equal(db.mutationCount, 0); });
test("deadline, fanout and invalid identity fail closed", async () => { const db = new FakeD1(); await assert.rejects(() => executeWrite(db, request({ actualFanout: 2 }))); await assert.rejects(() => executeWrite(db, request({ tenantId: "" }))); await assert.rejects(() => executeWrite(db, request({ deadlineAt: Date.now() - 1 }))); assert.equal(db.mutationCount, 0); });
test("tenant binding isolates the same idempotency key", async () => { const db = new FakeD1(); await executeWrite(db, request()); const result = await executeWrite(db, request({ tenantId: "tenant-2" })); assert.equal(result.status, "COMMITTED"); assert.equal(db.mutationCount, 2); });
